# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fac4dc78a3d3db3a156965b74d92df3c5f66333d013dce894f4776a5b9d090b7e56abe5e13a242aa1c48309412b3850c3ee63c45af955314ccf3c0e392df93ec

test:
  secret_key_base: 21185264290015c5d00da819fcbf6258679f622abd9e4acca6258c432a0c0bfa8c123e43f6556b0b92c4cfe623046b835fd13c3d9003b2409bcfd3c5e43c8916

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
